### ISSUE TITLE
ServiceResolver exception while manipulating resolved IP string

### ISSUE THREAD

**Issue by ghost** [jmdns/jmdns#161]
05-31 12:51:52.176 7128-8647/
W/JmDNSImpl: 192-168-232-2.local.recover() We are back!
05-31 12:51:50.133 7128-8400/ W/DNSResolverTask: ServiceResolver(192-168-232-2.local.).run() exception 
                                                                         java.lang.StringIndexOutOfBoundsException: String index out of range: -1
                                                                             at java.lang.String.substring(String.java:1975)
                                                                             at javax.jmdns.impl.ServiceInfoImpl.decodeQualifiedNameMapForType(ServiceInfoImpl.java:291)
                                                                             at javax.jmdns.impl.DNSEntry.<init>(DNSEntry.java:47)
                                                                             at javax.jmdns.impl.DNSQuestion.<init>(DNSQuestion.java:220)
                                                                             at javax.jmdns.impl.DNSQuestion$Pointer.<init>(DNSQuestion.java:89)
                                                                             at javax.jmdns.impl.DNSQuestion.newQuestion(DNSQuestion.java:249)
                                                                             at javax.jmdns.impl.tasks.resolver.ServiceResolver.addQuestions(ServiceResolver.java:64)
                                                                             at javax.jmdns.impl.tasks.resolver.DNSResolverTask.run(DNSResolverTask.java:69)
                                                                             at java.util.TimerThread.mainLoop(Timer.java:555)
                                                                             at java.util.TimerThread.run(Timer.java:505)
05-31 12:51:50.161 7128-8647/x W/JmDNSImpl: RECOVERING

how can I figure out this issue?

**Comment by derabbink** [comment]
I ran into the same issue, with a service descriptor looking like `_a_._b` or `_a_._b.`
I found this old [stackoverflow answer][1] which recommends you work around the issue by using `_a_._b.local.` instead. For me this worked.

I also found an [old bug from 2011 on sourceforge.com][2], which supposedly has been fixed by [SVN commit r320][3] (equivalent of 57f6e20d77f3f137572ec8c98eb8681d775206ca in git).

Yet, here we are.

[1]: https://stackoverflow.com/a/24689962/1296709
[2]: https://sourceforge.net/p/jmdns/bugs/101/
[3]: https://sourceforge.net/p/jmdns/code/320/

**Comment by melloware** [comment]
@kaikreuzer this is no longer an issue as this code has been completely rewriten and fixed in `ServiceTypeDecoder` class
