### ISSUE TITLE
Attempt to invoke virtual method 'boolean java.net.InetAddress.equals(java.lang.Object)'

### ISSUE THREAD

**Issue by casolorz** [jmdns/jmdns#162]
Saw this on my logs, not sure how it happened. JMDns 3.5.3 on Android 8.1

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.InetAddress.equals(java.lang.Object)' on a null object reference
        at libcore.io.IoBridge.postRecvfrom(IoBridge.java:612)
        at libcore.io.IoBridge.recvfrom(IoBridge.java:584)
        at java.net.PlainDatagramSocketImpl.doRecv(PlainDatagramSocketImpl.java:153)
        at java.net.PlainDatagramSocketImpl.receive0(PlainDatagramSocketImpl.java:141)
        at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:162)
        at java.net.DatagramSocket.receive(DatagramSocket.java:847)
        at javax.jmdns.impl.SocketListener.run(SocketListener.java:41)
```

**Comment by EigenIsCoding** [comment]
I have the same issue.

**Comment by EigenIsCoding** [comment]
I have the  same issue. 
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.net.InetAddress.equals(java.lang.Object)' on a null object reference
       at javax.jmdns.impl.DNSRecord$Address.sameValue(DNSRecord.java:302)
       at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1359)
       at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1417)
       at javax.jmdns.impl.SocketListener.run(SocketListener.java:61)
```
When I traced the code, I found a piece of code that confused me。 in package javax.jmdns.impl class: DNSRecord
this.getAddress() always be null, so why is it. help me, thx
```
        boolean sameValue(DNSRecord other) {
            if (!(other instanceof DNSRecord.Address)) {
                return false;
            } else {
                DNSRecord.Address address = (DNSRecord.Address)other;
                return this.getAddress() == null && address.getAddress() != null ? false : this.getAddress().equals(address.getAddress());
            }
        }
```
