### ISSUE TITLE
Exception in JmDNSImpl.cleanCache() can result in crash while logging

### ISSUE THREAD

**Issue by bubbleguuum** [jmdns/jmdns#192]
There's this weird Exception caught in JmDNSImpl.cleanCache() in its catch block.

```
[JmDNS(192-168-9-144.local.).] SEVERE - 3:31:43.252 - 192-168-9-144.local..Error while reaping records: [IPv6Address@251721178 type: TYPE_AAAA index 28, class: CLASS_IN index 1-unique, name: 18ddc089-2ea5-4080-9dca-47bb1805191f.local. ttl: '54/120' address: '0.0.0.0']
java.lang.ClassCastException: java.net.Inet4Address cannot be cast to java.net.Inet6Address
at com.amazon.whisperlink.jmdns.impl.DNSRecord$IPv6Address.getServiceInfo(DNSRecord.java:254)
at com.amazon.whisperlink.jmdns.impl.DNSRecord.getServiceInfo(DNSRecord.java:995)
at com.amazon.whisperlink.jmdns.impl.JmDNSImpl.renewServiceCollector(JmDNSImpl.java:1308)
at com.amazon.whisperlink.jmdns.impl.JmDNSImpl.cleanCache(JmDNSImpl.java:1887)
at com.amazon.whisperlink.jmdns.impl.tasks.RecordReaper.run(RecordReaper.java:58)

```

The stack trace reference a jMDNS version embedded in the Amazon Fling SDK but I think this issue applies to current master as well.
It shows that DNSRecord$IPv6Address.getServiceInfo() is trying to cast Inet4Address to Inet6Address which is weird and probably a bug in itself. Problem is that it triggers a crash in the catch block which calls toString() on the JmDNSImpl instance:

```
java.lang.NoSuchMethodError: No virtual method keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView; in class Lcom/amazon/whisperlink/jmdns/impl/DNSCache; or its super classes
at com.amazon.whisperlink.jmdns.impl.DNSCache.toString(DNSCache.java:383)
at com.amazon.whisperlink.jmdns.impl.JmDNSImpl.toString(JmDNSImpl.java:2010)
at com.amazon.whisperlink.jmdns.impl.JmDNSImpl.cleanCache(JmDNSImpl.java:1891)
at com.amazon.whisperlink.jmdns.impl.tasks.RecordReaper.run(RecordReaper.java:58)
```

**Comment by kaikreuzer** [comment]
Sorry, but those exceptions are not from JmDNS, which lives in the `javax.jmdns` namespace and not under `com.amazon`. I assume this is some fork that Amazon has done?

Feel free to reopen this issue, if you can reproduce it with the official JmDNS release as well.

**Comment by bubbleguuum** [comment]
OK. forget it.
