### ISSUE TITLE
Security violations in tests

### ISSUE THREAD

**Issue by rhwood** [jmdns/jmdns#196]
Tests that attempt to clear the ZeroConfManager often hit a Security violation, at least when run on an OpenJDK version of Java (such as used on Travis CI or on my MacBook):

```
Exception in thread "dns.close in ZeroConfServiceManager#stopAll" java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.util.concurrent.ThreadPoolExecutor.checkShutdownAccess(ThreadPoolExecutor.java:748)
	at java.base/java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1373)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.shutdown(Executors.java:690)
	at javax.jmdns.impl.JmDNSImpl.close(JmDNSImpl.java:1935)
	at jmri.util.zeroconf.ZeroConfServiceManager.lambda$6(ZeroConfServiceManager.java:312)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.util.concurrent.ThreadPoolExecutor.checkShutdownAccess(ThreadPoolExecutor.java:748)
	at java.base/java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1373)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.shutdown(Executors.java:690)
	at javax.jmdns.impl.JmDNSImpl.close(JmDNSImpl.java:1935)
	at jmri.util.zeroconf.ZeroConfServiceManager.lambda$6(ZeroConfServiceManager.java:312)
	at java.base/java.lang.Thread.run(Thread.java:834)
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "modifyThread")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
	at java.base/java.util.concurrent.ThreadPoolExecutor.checkShutdownAccess(ThreadPoolExecutor.java:748)
	at java.base/java.util.concurrent.ThreadPoolExecutor.shutdown(ThreadPoolExecutor.java:1373)
	at java.base/java.util.concurrent.Executors$DelegatedExecutorService.shutdown(Executors.java:690)
	at javax.jmdns.impl.JmDNSImpl.close(JmDNSImpl.java:1935)
	at jmri.util.zeroconf.ZeroConfServiceManager.lambda$6(ZeroConfServiceManager.java:312)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rhwood** [comment]
This is triggered by calling `<my JmDNS instance>.close()`. Should I not be?

**Comment by janossch** [comment]
@rhwood I think you can definitely call `JmDNS.close()`. Does your application (maybe in this TravisCI) using `SecurityManager`?

Applications usually (which decides to use `SecurityManager`) uses a policy file, that might be specified in their command line. Probably (I'm not 100% sure) you need to grant "modifyThread" permission for your application..

Nevertheless if you can wait circa 4 more years 😀 your problem will self destruct since `SecurityManager` has been deprecated in [JDK17](https://openjdk.org/jeps/411) and they will remove it in a future JDK release. See https://openjdk.org/jeps/486

Cc: @melloware @kaikreuzer

**Comment by rhwood** [comment]
I left that project about 6 months I filed this, so yep, it can wait.
