### ISSUE TITLE
Version 3.5.6 crash with java.util.ConcurrentModificationException in DNSCache

### ISSUE THREAD

**Issue by Tolriq** [jmdns/jmdns#211]
It seems the rewrite now triggers java.util.ConcurrentModificationException: 

Unfortunately my stack trace does not embed line numbers due to R8 :( 

One of the getDNSEntry method is missing synchronization it seems.

```
java.util.ConcurrentModificationException: 
  at java.util.ArrayList$Itr.next (ArrayList.java:860)
  at javax.jmdns.impl.DNSCache.getDNSEntry (DNSCache.java)
  at javax.jmdns.impl.JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getName (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSEntry.isUnique (DNSEntry.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getName (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord.getCreated (DNSRecord.java)
                      JmDNSImpl.isOlderThanOneSecond (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord.setWillExpireSoon (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.getTTL (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.setWillExpireSoon (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSEntry.sameSubtype (DNSEntry.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.resetTTL (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord$Pointer.getAlias (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
  at javax.jmdns.impl.JmDNSImpl.handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
  at javax.jmdns.impl.SocketListener.run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                      JmDNSImpl.getSocket (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
                      JmDNSImpl.getLocalHost (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      DNSMessage.isValidResponseCode (DNSMessage.java)
                      SocketListener.run (SocketListener.java)
                      JmDNSImpl.getGroup (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
```

**Comment by Tolriq** [comment]
Also triggers NPE:

```
java.lang.NullPointerException: 
  at javax.jmdns.impl.DNSCache.getDNSEntry (DNSCache.java)
  at javax.jmdns.impl.JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getName (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSEntry.isUnique (DNSEntry.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getName (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord.getCreated (DNSRecord.java)
                      JmDNSImpl.isOlderThanOneSecond (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord.setWillExpireSoon (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.getTTL (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.setWillExpireSoon (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSEntry.sameSubtype (DNSEntry.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSRecord.resetTTL (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                      DNSCache.replaceDNSEntry (DNSCache.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                                getCache (JmDNSImpl.java)
                                handleRecord (JmDNSImpl.java)
                      DNSRecord$Pointer.getAlias (DNSRecord.java)
                      JmDNSImpl.handleRecord (JmDNSImpl.java)
  at javax.jmdns.impl.JmDNSImpl.handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
                                aRecordsLast (JmDNSImpl.java)
                                handleResponse (JmDNSImpl.java)
  at javax.jmdns.impl.SocketListener.run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                                     sleepThread (SocketListener.java)
                                     run (SocketListener.java)
                      JmDNSImpl.getSocket (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
                      JmDNSImpl.getLocalHost (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.getInetAddress (HostInfo.java)
                               shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      HostInfo.shouldIgnorePacket (HostInfo.java)
                      SocketListener.run (SocketListener.java)
                      DNSMessage.isValidResponseCode (DNSMessage.java)
                      SocketListener.run (SocketListener.java)
                      JmDNSImpl.getGroup (JmDNSImpl.java)
                      SocketListener.run (SocketListener.java)
```

**Comment by bubbleguuum** [comment]
Also seen this one with 3.5.6. Not looking good :(

```
java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
	at javax.jmdns.impl.DNSCache.toString(DNSCache.java:288)
	at javax.jmdns.impl.JmDNSImpl.toString(JmDNSImpl.java:2006)
	at javax.jmdns.impl.JmDNSImpl.cleanCache(JmDNSImpl.java:1914)
	at javax.jmdns.impl.tasks.RecordReaper.run(RecordReaper.java:56)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
	at java.base/java.util.TimerThread.run(Timer.java:506)
```

**Comment by Tolriq** [comment]
Yes I've reverted as the related commit triggering this https://github.com/jmdns/jmdns/commit/6d747fb5dd9d36fc781d6dac056881b10585ff9c#diff-d826461043f11baaf9b1b1ef0280249045ee1ffa6e06fe03c7652424fd06d314 is not very clear to propose a fix.

**Comment by bubbleguuum** [comment]
Thanks for the tip :).
However, does reverting that commit will cause that d8 desugaring issue it was supposed to fix ?
It seemed like the wrong fix anyway, as it is better to understand what caused d8 to fail (and maybe it doesn't anymore, with up to date d8 ?) and reported to the d8 dev team.

**Comment by Tolriq** [comment]
Never had any R8/D8 issue with jmdDNS or I would have reported it ;) Probably some old version or configuration issue but min API 21.

**Comment by tmm1** [comment]
I'm seeing the same issues:

```
NullPointerException: Attempt to invoke virtual method 'h.a.g.t.e h.a.g.b.f()' on a null object reference
    at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1373)
    at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1476)
    at javax.jmdns.impl.SocketListener.run(SocketListener.java:77)
```

```
ConcurrentModificationException: None
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at javax.jmdns.impl.DNSCache.getDNSEntry(DNSCache.java:142)
    at javax.jmdns.impl.JmDNSImpl.getServiceInfoFromCache(JmDNSImpl.java:787)
    at javax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1290)
    at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1447)
```

```
ConcurrentModificationException: None
    at java.util.ArrayList$Itr.next(ArrayList.java:860)
    at javax.jmdns.impl.DNSCache.getDNSEntry(DNSCache.java:142)
    at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1362)
    at javax.jmdns.impl.JmDNSImpl.handleResponse(JmDNSImpl.java:1476)
    at javax.jmdns.impl.SocketListener.run(SocketListener.java:77)
 ```

**Comment by kaikreuzer** [comment]
@MWingbermuhle Wdyt? Shall we revert #208?

**Comment by MWingbermuhle** [comment]
@kaikreuzer I still have a hard time in understanding what can cause the ConcurrentModificationExceptions and NPE's with the changes that I did. There are indeed some changes in synchronization but those should not have such dramatic impact.

Anyway, the last thing that I heard/read about the R8/D8 desugaring issue that Google had patched an actual bug that could cause issues similar to what I saw with JmDNS, and worked around with #208. Our team is now running Android SDK 30, so possibly the R8/D8 issue is not applicable anymore. Feel free to revert the fixes and see if that improves the situation. I still have the choice to not upgrade to version 3.5.7 (yet). 

If anyone has a clear picture/story on how these issues came to manifest themselves now, please enlighten us.

**Comment by RGdevz** [comment]
I got this problem with the latest version will try with 3.5.6.

Device: Redmi Note 8 Pro
Error: java.lang.NoSuchMethodError: No static method $default$putIfAbsent(Ljava/util/concurrent/ConcurrentMap;Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lj$/util/concurrent/ConcurrentMap$-CC; or its super classes (declaration of 'j$.util.concurrent.ConcurrentMap$-CC' appears in base.apk!classes2.dex)
at d.a.g.a.putIfAbsent(Unknown Source:0)
at d.a.g.a.d(DNSCache.java:2)
at d.a.g.l.E0(JmDNSImpl.java:34)
at d.a.g.l.F0(JmDNSImpl.java:5)
at d.a.g.s.run(SocketListener.java:16)

Android Version: 11
App Version: 137
Date: 2021-11-12T20:13:38.292 02:00

**Comment by RGdevz** [comment]
the user reported the crash does not happend with 3.5.6
