### ISSUE TITLE
Rare StringIndexOutOfBoundsException in ServiceTypeDecoder.originalCase()

### ISSUE THREAD

**Issue by bubbleguuum** [jmdns/jmdns#246]
Seen this exception in an automated crash report for my program:

```
java.lang.StringIndexOutOfBoundsException: begin 48, end 54, length 53"
    at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
    at java.base/java.lang.String.substring(Unknown Source)
    at javax.jmdns.impl.ServiceTypeDecoder.originalCase(ServiceTypeDecoder.java:73)
    at javax.jmdns.impl.ServiceTypeDecoder.decodeQualifiedNameMapForType(ServiceTypeDecoder.java:62)
    at javax.jmdns.impl.DNSRecord$Pointer.getServiceInfo(DNSRecord.java:544)
    at javax.jmdns.impl.DNSRecord$Pointer.getServiceEvent(DNSRecord.java:555)
    at javax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1287)
    at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1447)
    at javax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1569)
    at javax.jmdns.impl.SocketListener.run(SocketListener.java:75)

```

Looking at `ServiceTypeDecoder`, crashing line is:

```
    return casePreservedType.substring(matcher.start(group), matcher.end(group));
```

For some reason, `matcher.end(group)` (with group=5) is returning an index value in the input string of the `Matcher`
greater than the string length (54 > 53). Maybe a funky `type` parameter to `decodeQualifiedNameMapForType()` with unicode chars or something ?

JRE is Eclipse Adoptium 11.0.13+8.

**Comment by ItsAMeNick** [comment]
I've been seeing this as well.

`java.lang.StringIndexOutOfBoundsException: begin 21, end 27, length 26
    at java.lang.String.checkBoundsBeginEnd(String.java:3942)
    at java.lang.String.substring(String.java:2467)
    at javax.jmdns.impl.ServiceTypeDecoder.originalCase(ServiceTypeDecoder.java:16)
    at javax.jmdns.impl.ServiceTypeDecoder.decodeQualifiedNameMapForType(ServiceTypeDecoder.java:130)
    at javax.jmdns.impl.DNSRecord$Pointer.getServiceInfo(DNSRecord.java:75)
    at javax.jmdns.impl.DNSRecord$Pointer.getServiceEvent(DNSRecord.java:2)
    at javax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1)
    at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:307)
    at javax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:99)
    at javax.jmdns.impl.SocketListener.run(SocketListener.java:158)`

**Comment by axlsml** [comment]
Hi guys,

any chance of finding out the type string that causes the error? Is that exception easiliy reproducible? Then you might just get a list of all available jmdns services with a tool like bonjour / zeroconf
https://www.tildesoft.com/

Which locale is your app running?

The javadoc does mention some locale-specifics here:
![image](https://github.com/jmdns/jmdns/assets/32395087/a892b0aa-1c64-42f7-af70-72b13048e5ed)

Thanks,
Axel

**Comment by plotczyktest** [comment]
`java.lang.StringIndexOutOfBoundsException: begin 31, end 37, length 36
  at java.lang.String.checkBoundsBeginEnd(String.java:3942)
  at java.lang.String.substring(String.java:2467)
  at javax.jmdns.impl.ServiceTypeDecoder.originalCase(ServiceTypeDecoder.java:73)
  at javax.jmdns.impl.ServiceTypeDecoder.decodeQualifiedNameMapForType(ServiceTypeDecoder.java:62)
  at javax.jmdns.impl.DNSRecord$Pointer.getServiceInfo(DNSRecord.java:544)
  at javax.jmdns.impl.DNSRecord$Pointer.getServiceEvent(DNSRecord.java:555)
  at javax.jmdns.impl.JmDNSImpl.updateRecord(JmDNSImpl.java:1262)
  at javax.jmdns.impl.JmDNSImpl.handleRecord(JmDNSImpl.java:1461)
  at javax.jmdns.impl.JmDNSImpl.handleQuery(JmDNSImpl.java:1583)
  at javax.jmdns.impl.SocketListener.run(SocketListener.java:75)`

same for us 
and we are not able to reproduce it or check what mdns records are causing this issue

**Comment by plotczyktest** [comment]
probably jmdsn records some record with type containing some strange char which in not properly LowerCased???
I can only think of this case for length mismatch between `casePreservedType` and `aType` with the later being matched by Matcher and the first one being substringed
`static Map<Fields, String> decodeQualifiedNameMapForType(String type) {
        int index;

        String casePreservedType = type;

        String aType = type.toLowerCase();
        String application = aType;
        String protocol = "";
        String subtype = "";
        String name = "";
        String domain = "";

        if (aType.contains("in-addr.arpa") || aType.contains("ip6.arpa")) {
            index = (aType.contains("in-addr.arpa") ? aType.indexOf("in-addr.arpa") : aType.indexOf("ip6.arpa"));
            name = ServiceInfoImpl.removeSeparators(casePreservedType.substring(0, index));
            domain = casePreservedType.substring(index);
            application = "";
        } else if ((!aType.contains("_")) && aType.contains(".")) {
            index = aType.indexOf('.');
            name = ServiceInfoImpl.removeSeparators(casePreservedType.substring(0, index));
            domain = ServiceInfoImpl.removeSeparators(casePreservedType.substring(index));
            application = "";
        } else {
            Matcher subType = SUBTYPE_PATTERN.matcher(aType);
            if (subType.matches()) {
                name = originalCase(casePreservedType, subType, 2);
                subtype = originalCase(casePreservedType, subType, 3);
                application = originalCase(casePreservedType, subType, 4);
                protocol = originalCase(casePreservedType, subType, 5);
                domain = originalCase(casePreservedType, subType, 6);
            } else {
                Matcher normalMatcher = PATTERN.matcher(aType);
                if (normalMatcher.matches()) {
                    name = originalCase(casePreservedType, normalMatcher, 2);
                    application = originalCase(casePreservedType, normalMatcher, 3);
                    protocol = originalCase(casePreservedType, normalMatcher, 4);
                    domain = originalCase(casePreservedType, normalMatcher, 5);
                }
            }
        }

        return ServiceInfoImpl.createQualifiedMap(name, ServiceInfoImpl.removeSeparators(application), protocol, ServiceInfoImpl.removeSeparators(domain), subtype);
    }`

```
private static String originalCase(String casePreservedType, Matcher matcher, int group) {
        if (matcher.start(group) != -1) {
            return casePreservedType.substring(matcher.start(group), matcher.end(group));
        }
        return "";
    }
```

**Comment by plotczyktest** [comment]
for example:
for 
final String type = "aBcİ._someapplication._tcp.local." which takes 67 chars

it gives you
aType = "abci̇._someapplication._tcp.local."  - which takes 69 chars
name = "aBcİ."
application = "omeapplication."
protocol = "cp."
domain -> crash java.lang.StringIndexOutOfBoundsException: length=33; index=34

**Comment by melloware** [comment]
@kaikreuzer this issue can be closed as the PR was merged and the bug is fixed

**Comment by bubbleguuum** [comment]
Thanks for the fix, closing.
