### ISSUE TITLE
com.google.inject.ProvisionException: Unable to provision

### ISSUE THREAD

**Issue by nc-jeni** [jmdns/jmdns#250]
API
Java

Operating System
Windows 11 - WSL Ubuntu

It works on other platforms that are non-wsl.

JDK
1.8

Expected Behavior
Listening to broadcasts and connect to them

Actual Behavior
Fatal error during startup, aborted
com.google.inject.ProvisionException: Unable to provision, see the following errors:
while locating XXX
while locating XXX annotated with @com.google.inject.internal.Element(setName=,uniqueId=19, type=MULTIBINDER, keyType=)

Error injecting constructor, java.net.SocketException: Invalid argument
Caused by: java.net.SocketException: Invalid argument
at java.net.PlainDatagramSocketImpl.join(Native Method)
at java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:178)
at java.net.MulticastSocket.joinGroup(MulticastSocket.java:323)
at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:463)
at javax.jmdns.impl.JmDNSImpl.(JmDNSImpl.java:420)
at javax.jmdns.JmDNS.create(JmDNS.java:81)

**Comment by melloware** [comment]
@nc-jeni i am running on WSL2 and Ubutnu without issues running 3.5.12.

```
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.3 LTS
Release:        22.04
Codename:       jammy
```

Can this be closed?

**Comment by melloware** [comment]
@kaikreuzer no repsonse from OP. Safe to close
