### ISSUE TITLE
ipv6

### ISSUE THREAD

**Issue by usnasoft** [jmdns/jmdns#260]
It seems that there is some issue on ipv6 enabled systems; this is a stack trace from an user (I was not able to reproduce the error on my systems):

java.net.SocketException: Invalid argument: no further information
        at java.base/sun.nio.ch.Net.setInterface6(Native Method)
        at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364)
        at java.base/sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:420)
        at java.base/sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:605)
        at java.base/java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:445)
        at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:484)
        at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:440)
        at javax.jmdns.JmDNS.create(JmDNS.java:164)
		...

I'm currently using version 3.5.9-SNAPSHOT (the fork is aligned).
The problem shows on java 17 where preference is on ipv6 (no issue with java 8) and can be solved with  -Djava.net.preferIPv4Stack=true on the command line (alas System.setProperty("java.net.preferIPv4Stack" , "true"); does not helps)

**Comment by usnasoft** [comment]
This issue is plobably related to this known jdk bug:
https://bugs.openjdk.org/browse/JDK-8272476
([JDK-8272476)

**Comment by melloware** [comment]
@kaikreuzer safe to close this ticket.
