### ISSUE TITLE
java.net.SocketException: Invalid argument: setsockopt

### ISSUE THREAD

**Issue by zhaohailongzhl** [jmdns/jmdns#273]
java.net.SocketException: Invalid argument: setsockopt
at java.base/sun.nio.ch.Net.setInterface6(Native Method) 
at java.base/sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364) 
at java.base/sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:420) 
at java.base/sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:605) 
at java.base/java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:445) 
at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:484) 
at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:440) 
at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:399) 
at javax.jmdns.JmDNS.create(JmDNS.java:78)

This problem occurs on some machines, window11, jdk: 17.0.11,jmdns version is 3.5.9, and here is my code：

public class DiscoverServices {
    static class SampleListener implements ServiceListener {
        public void serviceAdded(ServiceEvent event) {
            System.out.println("Service added   : " + event.getName()+"."+event.getType());
        }
        public void serviceRemoved(ServiceEvent event) {
            System.out.println("Service removed : " + event.getName()+"."+event.getType());
        }
        public void serviceResolved(ServiceEvent event) {
            System.out.println("Service resolved: " + event.getInfo());
        }
    }
    public static void main(String[] args) {
        try {
            JmDNS jmdns = JmDNS.create(InetAddress.getLocalHost());
            jmdns.addServiceListener("_http._tcp.local.", new SampleListener());
            int b;
            while ((b = System.in.read()) != -1 && (char) b != 'q');
            jmdns.close();
            System.out.println("Done");
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}

**Comment by zhaohailongzhl** [comment]
I'm using WiFi, how do I fix it

**Comment by mstevetodd** [comment]
I am still encountering this error with jmdns-3.5.12.jar. It is consistent when I disable IPv6 on the adapter..

java.net.SocketException: Invalid argument: setsockopt
	at sun.nio.ch.Net.setInterface6(Native Method) ~[?:?]
	at sun.nio.ch.DatagramChannelImpl.setOption(DatagramChannelImpl.java:364) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.setOption(DatagramSocketAdaptor.java:420) ~[?:?]
	at sun.nio.ch.DatagramSocketAdaptor.setNetworkInterface(DatagramSocketAdaptor.java:605) ~[?:?]
	at java.net.MulticastSocket.setNetworkInterface(MulticastSocket.java:445) ~[?:?]
	at javax.jmdns.impl.JmDNSImpl.openMulticastSocket(JmDNSImpl.java:484) ~[jmdns-3.5.12.jar:3.5.12]
	at javax.jmdns.impl.JmDNSImpl.<init>(JmDNSImpl.java:440) ~[jmdns-3.5.12.jar:3.5.12]
	at javax.jmdns.JmDNS.create(JmDNS.java:164) ~[jmdns-3.5.12.jar:3.5.12]
